#!/usr/bin/env python3
"""Generate headless.rs test file from all test ROMs in testroms/."""

import os
import re

BASE = "testroms"
OUT = "tests/headless.rs"

def sanitize(name):
    """Convert a ROM filename to a valid Rust identifier."""
    name = name.replace('.gb', '')
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    name = re.sub(r'_+', '_', name)
    name = name.strip('_').lower()
    # Ensure starts with letter
    if name and name[0].isdigit():
        name = 'n' + name
    return name

def collect_roms():
    """Collect all .gb test ROMs, categorized."""
    roms = []
    for root, dirs, files in os.walk(BASE):
        for f in sorted(files):
            if not f.endswith('.gb'):
                continue
            if 'Zone' in f:
                continue
            path = os.path.join(root, f)
            roms.append(path)
    roms.sort()
    return roms

def categorize(path):
    """Return (category, subcategory) for a ROM path."""
    if 'artifacts/blargg' in path:
        return 'blargg'
    elif 'artifacts/mooneye-test-suite' in path:
        return None  # skip duplicates
    elif 'mts-20240926' in path:
        return None  # skip duplicates
    elif 'artifacts/gbmicrotest' in path:
        return 'gbmicrotest'
    elif 'artifacts/age-test-roms' in path:
        return 'age'
    elif 'artifacts/mealybug-tearoom-tests' in path:
        return None  # skip, top-level copies exist
    elif 'artifacts/gambatte' in path:
        return 'gambatte'
    elif 'artifacts/' in path:
        return 'other'
    else:
        return 'mooneye'

def is_blargg(path):
    return 'artifacts/blargg' in path

def is_dmg_relevant(path):
    """Filter out CGB-only, SGB-only, etc."""
    name = os.path.basename(path).lower()
    # Skip CGB-specific
    if 'cgb' in name and 'dmg' not in name:
        return False
    # Skip SGB-specific
    if name.endswith('-s.gb') or 'sgb' in name:
        return False
    # Skip dmg0 (early DMG revision)
    if 'dmg0' in name:
        return False
    # Skip mgb (MGB-specific)
    if '-mgb' in name:
        return False
    # Skip nocgb/ncm variants
    if 'nocgb' in name or 'ncm' in name:
        return False
    # Skip -ds (double-speed CGB)
    if '-ds' in name or '_ds_' in name or '_ds-' in name:
        return False
    return True

def main():
    roms = collect_roms()

    categories = {}
    for path in roms:
        cat = categorize(path)
        if cat is None:
            continue
        if not is_dmg_relevant(path):
            continue
        categories.setdefault(cat, []).append(path)

    # Track used names to avoid duplicates
    used_names = set()

    lines = []
    lines.append('//! Headless test harness for Game Boy test ROMs.')
    lines.append('//!')
    lines.append('//! Auto-generated by generate_tests.py — do not edit manually.')
    lines.append('//!')
    lines.append('//! Run with: cargo test --no-default-features --test headless -- --nocapture')
    lines.append('')
    lines.append('use rustboy::cpu::CPU;')
    lines.append('use std::path::Path;')
    lines.append('')

    # Helper functions
    lines.append(r'''
/// Run a ROM for up to `max_cycles` M-cycles, stopping early if the
/// Mooneye finish signature is detected or a Blargg magic string appears.
fn run_rom(path: &str, max_cycles: u64) -> CPU {
    let rom = std::fs::read(path).unwrap_or_else(|e| panic!("Failed to read ROM {}: {}", path, e));
    let mut cpu = CPU::new();
    cpu.load_rom(rom);
    // Skip boot ROM — set PC to 0x100 and initialise post-boot state
    cpu.program_counter = 0x100;
    cpu.booting = false;
    // Standard DMG post-boot register values
    cpu.memory[0xFF05] = 0x00; // TIMA
    cpu.memory[0xFF06] = 0x00; // TMA
    cpu.memory[0xFF07] = 0x00; // TAC
    cpu.memory[0xFF40] = 0x91; // LCDC
    cpu.memory[0xFF41] = 0x85; // STAT
    cpu.memory[0xFF47] = 0xFC; // BGP
    cpu.memory[0xFF48] = 0xFF; // OBP0
    cpu.memory[0xFF49] = 0xFF; // OBP1
    cpu.memory[0xFFFF] = 0x00; // IE

    let mut total: u64 = 0;
    while total < max_cycles {
        cpu.handle_interrupts();
        if !cpu.halt {
            cpu.execute();
        } else {
            cpu.cycles += 1;
            cpu.tick_timer_4t();
        }
        let cycles = cpu.cycles as u64;
        let t_cycles = (cycles * 4) as u32;
        cpu.handle_timer(t_cycles);
        total += cycles;
        cpu.total_cycles += cycles;
        cpu.cycles = 0;

        // Detect JR -2 infinite loop (0x18 0xFE)
        let addr = cpu.program_counter as usize;
        if addr + 1 < cpu.memory.len()
            && cpu.memory[addr] == 0x18
            && cpu.memory[addr + 1] == 0xFE
        {
            break;
        }

        // Detect LD B,B (0x40) followed by JR -2 (Mooneye finish)
        if addr + 2 < cpu.memory.len()
            && cpu.memory[addr] == 0x40
            && cpu.memory[addr + 1] == 0x18
            && cpu.memory[addr + 2] == 0xFE
        {
            cpu.execute();
            cpu.cycles = 0;
            break;
        }
    }
    cpu
}

/// Check if a Mooneye test passed (B=3,C=5,D=8,E=13,H=21,L=34).
fn mooneye_passed(cpu: &CPU) -> bool {
    cpu.get_reg_b() == 3
        && cpu.get_reg_c() == 5
        && cpu.get_reg_d() == 8
        && cpu.get_reg_e() == 13
        && cpu.get_reg_h() == 21
        && cpu.get_reg_l() == 34
}

fn mooneye_state(cpu: &CPU) -> String {
    format!(
        "B={:02X} C={:02X} D={:02X} E={:02X} H={:02X} L={:02X} A={:02X} F={:02X} PC={:04X}",
        cpu.get_reg_b(), cpu.get_reg_c(), cpu.get_reg_d(), cpu.get_reg_e(),
        cpu.get_reg_h(), cpu.get_reg_l(), cpu.get_reg_a(), cpu.get_reg_f(),
        cpu.program_counter
    )
}

fn run_mooneye_test(rom_path: &str) {
    if !Path::new(rom_path).exists() {
        eprintln!("SKIP: ROM not found: {}", rom_path);
        return;
    }
    let cpu = run_rom(rom_path, 50_000_000);
    let state = mooneye_state(&cpu);
    let serial = String::from_utf8_lossy(&cpu.serial_output);
    println!("Test: {}", rom_path);
    println!("  Registers: {}", state);
    if !serial.is_empty() {
        println!("  Serial: {}", serial.replace('\n', " | "));
    }
    assert!(mooneye_passed(&cpu), "FAIL: {} — {}", rom_path, state);
}

fn run_blargg_test(rom_path: &str) {
    if !Path::new(rom_path).exists() {
        eprintln!("SKIP: ROM not found: {}", rom_path);
        return;
    }
    let cpu = run_rom(rom_path, 200_000_000);
    let serial = String::from_utf8_lossy(&cpu.serial_output);
    println!("Test: {}", rom_path);
    println!("  Serial: {}", serial.replace('\n', " | "));
    assert!(
        serial.contains("Passed"),
        "FAIL: {} — serial: {}",
        rom_path,
        serial.replace('\n', " | ")
    );
}
''')

    # Generate Mooneye tests
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('// Mooneye acceptance tests')
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('')

    for path in categories.get('mooneye', []):
        name = sanitize(os.path.relpath(path, BASE))
        # Prefix with mooneye_ for clarity
        full_name = f'mooneye_{name}'
        if full_name in used_names:
            continue
        used_names.add(full_name)
        lines.append(f'#[test]')
        lines.append(f'fn {full_name}() {{')
        lines.append(f'    run_mooneye_test("{path}");')
        lines.append(f'}}')
        lines.append('')

    # Generate Blargg tests
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('// Blargg tests')
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('')

    for path in categories.get('blargg', []):
        name = sanitize(os.path.basename(path))
        full_name = f'blargg_{name}'
        if full_name in used_names:
            continue
        used_names.add(full_name)
        lines.append(f'#[test]')
        lines.append(f'fn {full_name}() {{')
        lines.append(f'    run_blargg_test("{path}");')
        lines.append(f'}}')
        lines.append('')

    # Generate gbmicrotest tests (these use Mooneye pass/fail convention)
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('// GBMicrotest tests')
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('')

    for path in categories.get('gbmicrotest', []):
        name = sanitize(os.path.basename(path))
        full_name = f'micro_{name}'
        if full_name in used_names:
            full_name += '_2'
        if full_name in used_names:
            continue
        used_names.add(full_name)
        lines.append(f'#[test]')
        lines.append(f'fn {full_name}() {{')
        lines.append(f'    run_mooneye_test("{path}");')
        lines.append(f'}}')
        lines.append('')

    # Generate quick unit tests for timer mechanics
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('// Unit tests for timer mechanics')
    lines.append('// ══════════════════════════════════════════════════════════════════')
    lines.append('')
    lines.append(r'''
#[test]
fn timer_falling_edge_basic() {
    let mut cpu = CPU::new();
    cpu.program_counter = 0x100;
    cpu.booting = false;
    cpu.memory[0xFF05] = 0x00;
    cpu.memory[0xFF06] = 0x00;
    cpu.memory[0xFF07] = 0x00;
    cpu.write_byte(0xFF07, 0x05); // 262144 Hz
    for _ in 0..4 { cpu.tick_timer_4t(); }
    assert_eq!(cpu.memory[0xFF05], 1, "TIMA should be 1 after 4 M-cycles at 262144 Hz");
}

#[test]
fn timer_div_reset_causes_tick() {
    let mut cpu = CPU::new();
    cpu.program_counter = 0x100;
    cpu.booting = false;
    cpu.memory[0xFF05] = 0x00;
    cpu.memory[0xFF06] = 0x00;
    cpu.write_byte(0xFF07, 0x04); // 4096 Hz, monitors bit 9
    for _ in 0..128 { cpu.tick_timer_4t(); } // bit 9 is now 1
    let tima_before = cpu.memory[0xFF05];
    cpu.write_byte(0xFF04, 0x00); // DIV reset → falling edge
    assert_eq!(cpu.memory[0xFF05], tima_before + 1, "DIV reset should cause TIMA tick");
}
''')

    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))

    total = sum(len(v) for v in categories.values())
    print(f"Generated {OUT} with {len(used_names)} tests from {total} ROMs")
    for cat, paths in sorted(categories.items()):
        print(f"  {cat}: {len(paths)}")

if __name__ == '__main__':
    main()

