#!/usr/bin/env python3
"""Generate ROM tests from the curated registry, without duplicating the harness.

Add new ROMs to tests/rom_cases.json with runner micro, mooneye, or blargg.
Record unsupported hardware/result protocols explicitly with an ignore reason.
Missing files fail at runtime; they must never count as successful tests.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def main():
    cases = json.loads((ROOT / "tests/rom_cases.json").read_text())
    lines = [
        "//! Automated ROM tests. Generated by generate_tests.py; do not edit manually.",
        "//! Run: cargo test --no-default-features --test headless -- --nocapture",
        "//! TRACE_TEST=<ROM substring> enables tracing; TRACE_CSV=1 exports it.",
        "",
        'include!("support/rom_harness.rs");',
        "",
    ]
    names = set()
    for case in cases:
        name, runner, path = case["name"], case["runner"], case["path"]
        assert name.isidentifier() and name not in names, name
        assert runner in ("micro", "mooneye", "blargg"), runner
        names.add(name)
        lines.append("#[test]")
        if case.get("ignore"):
            lines.append(f'#[ignore = {json.dumps(case["ignore"])}]')
        lines.extend([
            f"fn {name}() {{",
            f"    run_{runner}_test({json.dumps(path)});",
            "}",
            "",
        ])
    (ROOT / "tests/headless.rs").write_text("\n".join(lines))
    ignored = sum(bool(case.get("ignore")) for case in cases)
    print(f"Generated {len(cases)} ROM tests ({ignored} explicitly ignored)")


if __name__ == "__main__":
    main()
