import assert from 'node:assert/strict';
import {ControllerInputs, gamepadButtons} from '../web/controller-input.mjs';

const pad = (index, pressed = [], axes = [0,0]) => ({index, id:`Test pad ${index}`, connected:true, mapping:'standard', axes,
  buttons:Array.from({length:16}, (_,i) => ({pressed:pressed.includes(i)}))});
assert.deepEqual([...gamepadButtons(pad(0,[0,1,8,9,12,15],[-0.8,0.8]))], ['up','down','left','right','a','b','start','select']);
assert.deepEqual([...gamepadButtons(pad(0,[],[0.5,-0.5]))], []);
const events = [], assignments = [];
const inputs = new ControllerInputs((...args) => events.push(args), value => assignments.push(value));
inputs.set('keyboard',0,'a',true);
inputs.set('touch1',0,'a',true);
inputs.poll([pad(4,[1]),pad(8,[0]),pad(9,[9]),pad(10,[8]),pad(11,[1])]);
assert.deepEqual(events, [[0,'a',true],[1,'b',true],[2,'start',true],[3,'select',true]]);
inputs.set('keyboard',0,'a',false);
inputs.set('touch1',0,'a',false);
assert.equal(events.length,4, 'pad keeps player one A held after keyboard/touch release');
inputs.poll([pad(4,[1]),pad(9,[9]),pad(10,[8]),pad(11,[1])]);
assert.deepEqual([...inputs.pads].map(([id,value]) => [id,value.port]), [[4,0],[9,2],[10,3],[11,1]]);
assert.deepEqual(events.slice(-2), [[1,'b',false],[1,'a',true]], 'disconnect releases and a waiting fifth pad fills free port');
inputs.clear();
const released = events.length;
inputs.poll([pad(4,[1]),pad(9,[9]),pad(10,[8]),pad(11,[1])]);
assert.equal(events.length,released, 'reset suppresses all held pads until neutral');
inputs.poll([pad(4),pad(9),pad(10),pad(11)]);
inputs.poll([pad(4,[1])]);
assert.deepEqual(events.at(-1), [0,'a',true]);
inputs.suspend(true);
inputs.set('keyboard',0,'b',true);
inputs.poll([pad(4,[0])]);
inputs.suspend(false);
const resumed = events.length;
inputs.set('keyboard',0,'b',true);
inputs.poll([pad(4,[0])]);
assert.equal(events.length,resumed, 'controls held while unfocused remain suppressed');
inputs.set('keyboard',0,'b',false);
inputs.poll([pad(4)]);
inputs.set('keyboard',0,'b',true);
assert.deepEqual(events.at(-1),[0,'b',true]);
inputs.poll([{...pad(7,[1]), mapping:''}]);
assert.equal(inputs.pads.size,0,'nonstandard gamepads are not guessed');
inputs.set('invalid',4,'a',true);
inputs.set('invalid',0,'x',true);
assert.deepEqual(assignments.at(-1), []);
console.log('Controller inputs: mapping, union, four stable ports, fifth-pad limit, disconnect, neutral suppression and focus passed');
