//! Headless test harness for Game Boy test ROMs.
//!
//! Auto-generated by generate_tests.py — do not edit manually.
//!
//! Run with: cargo test --no-default-features --test headless -- --nocapture

use rustboy::cpu::CPU;
use std::path::Path;


/// Run a ROM for up to `max_cycles` M-cycles, stopping early if the
/// Mooneye finish signature is detected or a Blargg magic string appears.
fn run_rom(path: &str, max_cycles: u64) -> CPU {
    let rom = std::fs::read(path).unwrap_or_else(|e| panic!("Failed to read ROM {}: {}", path, e));

    // Read the actual boot ROM (Adjust the path to match your project structure)
    let boot_rom = std::fs::read("roms/DMG_ROM.bin")
        .expect("Failed to read boot ROM. Ensure roms/DMG_ROM.bin exists.");

    let mut cpu = CPU::new();
    cpu.bootload(boot_rom);
    cpu.load_rom(rom);

    // REMOVE the manual overrides. Let the CPU start at 0x0000 with booting = true
    // cpu.program_counter = 0x100;
    // cpu.booting = false;
    // cpu.memory[0xFF05] = 0x00; ...

    let mut total: u64 = 0;
    while total < max_cycles {
        cpu.handle_interrupts();
        cpu.execute();

        let cycles = cpu.cycles as u64;
        let t_cycles = (cycles * 4) as u32;
        cpu.handle_timer(t_cycles);
        total += cycles;
        cpu.total_cycles += cycles;
        cpu.cycles = 0;

        // Detect JR -2 infinite loop (0x18 0xFE)
        let addr = cpu.program_counter as usize;
        if addr + 1 < cpu.memory.len()
            && cpu.memory[addr] == 0x18
            && cpu.memory[addr + 1] == 0xFE
        {
            break;
        }

        // Detect LD B,B (0x40) followed by JR -2 (Mooneye finish)
        if addr + 2 < cpu.memory.len()
            && cpu.memory[addr] == 0x40
            && cpu.memory[addr + 1] == 0x18
            && cpu.memory[addr + 2] == 0xFE
        {
            cpu.execute();
            cpu.cycles = 0;
            break;
        }
    }
    cpu
}

/// Check if a Mooneye test passed (B=3,C=5,D=8,E=13,H=21,L=34).
fn mooneye_passed(cpu: &CPU) -> bool {
    cpu.get_reg_b() == 3
        && cpu.get_reg_c() == 5
        && cpu.get_reg_d() == 8
        && cpu.get_reg_e() == 13
        && cpu.get_reg_h() == 21
        && cpu.get_reg_l() == 34
}

fn mooneye_state(cpu: &CPU) -> String {
    format!(
        "B={:02X} C={:02X} D={:02X} E={:02X} H={:02X} L={:02X} A={:02X} F={:02X} PC={:04X}",
        cpu.get_reg_b(), cpu.get_reg_c(), cpu.get_reg_d(), cpu.get_reg_e(),
        cpu.get_reg_h(), cpu.get_reg_l(), cpu.get_reg_a(), cpu.get_reg_f(),
        cpu.program_counter
    )
}

fn run_micro_test(rom_path: &str) {
    if !Path::new(rom_path).exists() {
        eprintln!("SKIP: ROM not found: {}", rom_path);
        return;
    }
    // These tests usually finish very quickly (a few hundred cycles)
    let cpu = run_rom(rom_path, 10_000_000);

    let test_result = cpu.peek_byte(0xFF80);
    let expected    = cpu.peek_byte(0xFF81);
    let pass_flag   = cpu.peek_byte(0xFF82);

    println!("Test: {}", rom_path);
    println!("  Memory: [0xFF80]={:02X}, [0xFF81]={:02X}, [0xFF82]={:02X}",
             test_result, expected, pass_flag);

    // Pass condition: 0xFF82 must be 0x01
    assert_eq!(pass_flag, 0x01,
               "FAIL: {} - Got {:02X}, Expected {:02X}",
               rom_path, test_result, expected);
}
fn run_mooneye_test(rom_path: &str) {
    if !Path::new(rom_path).exists() {
        eprintln!("SKIP: ROM not found: {}", rom_path);
        return;
    }
    let cpu = run_rom(rom_path, 50_000_000);
    let state = mooneye_state(&cpu);
    let serial = String::from_utf8_lossy(&cpu.serial_output);
    println!("Test: {}", rom_path);
    println!("  Registers: {}", state);
    if !serial.is_empty() {
        println!("  Serial: {}", serial.replace('\n', " | "));
    }
    assert!(mooneye_passed(&cpu), "FAIL: {} — {}", rom_path, state);
}

fn run_blargg_test(rom_path: &str) {
    if !Path::new(rom_path).exists() {
        eprintln!("SKIP: ROM not found: {}", rom_path);
        return;
    }
    let cpu = run_rom(rom_path, 200_000_000);
    let serial = String::from_utf8_lossy(&cpu.serial_output).to_string();
    println!("Test: {}", rom_path);

    // Blargg tests output results to BOTH serial AND RAM at 0xA004+
    // (with magic signature DE B0 61 at 0xA001-0xA003).
    // "rom_singles" variants only write to RAM, not serial.
    let has_ram_signature = cpu.peek_byte(0xA001) == 0xDE
        && cpu.peek_byte(0xA002) == 0xB0
        && cpu.peek_byte(0xA003) == 0x61;

    let mut ram_text = String::new();
    if has_ram_signature {
        for i in 0xA004..0xA200 {
            let b = cpu.peek_byte(i);
            if b == 0 { break; }
            ram_text.push(b as char);
        }
    }

    let output = if !serial.is_empty() { &serial } else { &ram_text };

    if !serial.is_empty() {
        println!("  Serial: {}", serial.replace('\n', " | "));
    }
    if !ram_text.is_empty() {
        println!("  RAM: {}", ram_text.replace('\n', " | "));
    }

    assert!(
        output.contains("Passed"),
        "FAIL: {} — output: {}",
        rom_path,
        output.replace('\n', " | ")
    );
}

// ══════════════════════════════════════════════════════════════════
// Mooneye acceptance tests
// ══════════════════════════════════════════════════════════════════

#[test]
fn mooneye_add_sp_e_timing() {
    run_mooneye_test("testroms/add_sp_e_timing.gb");
}

#[test]
fn mooneye_basic() {
    run_mooneye_test("testroms/basic.gb");
}

#[test]
fn mooneye_bits_bank1() {
    run_mooneye_test("testroms/bits_bank1.gb");
}

#[test]
fn mooneye_bits_bank2() {
    run_mooneye_test("testroms/bits_bank2.gb");
}

#[test]
fn mooneye_bits_mode() {
    run_mooneye_test("testroms/bits_mode.gb");
}

#[test]
fn mooneye_bits_ramg() {
    run_mooneye_test("testroms/bits_ramg.gb");
}

#[test]
fn mooneye_boot_div_dmgabcmgb() {
    run_mooneye_test("testroms/boot_div-dmgABCmgb.gb");
}

#[test]
fn mooneye_boot_hwio_dmgabcmgb() {
    run_mooneye_test("testroms/boot_hwio-dmgABCmgb.gb");
}

#[test]
fn mooneye_boot_regs_dmgabc() {
    run_mooneye_test("testroms/boot_regs-dmgABC.gb");
}

#[test]
fn mooneye_call_cc_timing() {
    run_mooneye_test("testroms/call_cc_timing.gb");
}

#[test]
fn mooneye_call_cc_timing2() {
    run_mooneye_test("testroms/call_cc_timing2.gb");
}

#[test]
fn mooneye_call_timing() {
    run_mooneye_test("testroms/call_timing.gb");
}

#[test]
fn mooneye_call_timing2() {
    run_mooneye_test("testroms/call_timing2.gb");
}

#[test]
fn mooneye_daa() {
    run_mooneye_test("testroms/daa.gb");
}

#[ignore]
#[test]
fn mooneye_di_timing_gs() {
    run_mooneye_test("testroms/di_timing-GS.gb");
}

#[test]
fn mooneye_div_timing() {
    run_mooneye_test("testroms/div_timing.gb");
}

#[test]
fn mooneye_ei_sequence() {
    run_mooneye_test("testroms/ei_sequence.gb");
}

#[test]
fn mooneye_ei_timing() {
    run_mooneye_test("testroms/ei_timing.gb");
}

#[test]
fn mooneye_halt_ime0_ei() {
    run_mooneye_test("testroms/halt_ime0_ei.gb");
}

#[test]
fn mooneye_halt_ime0_nointr_timing() {
    run_mooneye_test("testroms/halt_ime0_nointr_timing.gb");
}

#[test]
fn mooneye_halt_ime1_timing() {
    run_mooneye_test("testroms/halt_ime1_timing.gb");
}

#[ignore]
#[test]
fn mooneye_halt_ime1_timing2_gs() {
    run_mooneye_test("testroms/halt_ime1_timing2-GS.gb");
}

#[test]
fn mooneye_if_ie_registers() {
    run_mooneye_test("testroms/if_ie_registers.gb");
}

#[test]
fn mooneye_intr_timing() {
    run_mooneye_test("testroms/intr_timing.gb");
}

#[test]
fn mooneye_jp_cc_timing() {
    run_mooneye_test("testroms/jp_cc_timing.gb");
}

#[test]
fn mooneye_jp_timing() {
    run_mooneye_test("testroms/jp_timing.gb");
}

#[test]
fn mooneye_ld_hl_sp_e_timing() {
    run_mooneye_test("testroms/ld_hl_sp_e_timing.gb");
}

#[ignore]
#[test]
fn mooneye_m2_win_en_toggle() {
    run_mooneye_test("testroms/m2_win_en_toggle.gb");
}

#[ignore]
#[test]
fn mooneye_m3_bgp_change() {
    run_mooneye_test("testroms/m3_bgp_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_bgp_change_sprites() {
    run_mooneye_test("testroms/m3_bgp_change_sprites.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_bg_en_change() {
    run_mooneye_test("testroms/m3_lcdc_bg_en_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_bg_en_change2() {
    run_mooneye_test("testroms/m3_lcdc_bg_en_change2.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_bg_map_change() {
    run_mooneye_test("testroms/m3_lcdc_bg_map_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_bg_map_change2() {
    run_mooneye_test("testroms/m3_lcdc_bg_map_change2.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_obj_en_change() {
    run_mooneye_test("testroms/m3_lcdc_obj_en_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_obj_en_change_variant() {
    run_mooneye_test("testroms/m3_lcdc_obj_en_change_variant.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_obj_size_change() {
    run_mooneye_test("testroms/m3_lcdc_obj_size_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_obj_size_change_scx() {
    run_mooneye_test("testroms/m3_lcdc_obj_size_change_scx.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_tile_sel_change() {
    run_mooneye_test("testroms/m3_lcdc_tile_sel_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_tile_sel_change2() {
    run_mooneye_test("testroms/m3_lcdc_tile_sel_change2.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_tile_sel_win_change() {
    run_mooneye_test("testroms/m3_lcdc_tile_sel_win_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_tile_sel_win_change2() {
    run_mooneye_test("testroms/m3_lcdc_tile_sel_win_change2.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_win_en_change_multiple() {
    run_mooneye_test("testroms/m3_lcdc_win_en_change_multiple.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_win_en_change_multiple_wx() {
    run_mooneye_test("testroms/m3_lcdc_win_en_change_multiple_wx.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_win_map_change() {
    run_mooneye_test("testroms/m3_lcdc_win_map_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_lcdc_win_map_change2() {
    run_mooneye_test("testroms/m3_lcdc_win_map_change2.gb");
}

#[ignore]
#[test]
fn mooneye_m3_obp0_change() {
    run_mooneye_test("testroms/m3_obp0_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_scx_high_5_bits() {
    run_mooneye_test("testroms/m3_scx_high_5_bits.gb");
}

#[ignore]
#[test]
fn mooneye_m3_scx_high_5_bits_change2() {
    run_mooneye_test("testroms/m3_scx_high_5_bits_change2.gb");
}

#[ignore]
#[test]
fn mooneye_m3_scx_low_3_bits() {
    run_mooneye_test("testroms/m3_scx_low_3_bits.gb");
}

#[ignore]
#[test]
fn mooneye_m3_scy_change() {
    run_mooneye_test("testroms/m3_scy_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_scy_change2() {
    run_mooneye_test("testroms/m3_scy_change2.gb");
}

#[ignore]
#[test]
fn mooneye_m3_window_timing() {
    run_mooneye_test("testroms/m3_window_timing.gb");
}

#[ignore]
#[test]
fn mooneye_m3_window_timing_wx_0() {
    run_mooneye_test("testroms/m3_window_timing_wx_0.gb");
}

#[ignore]
#[test]
fn mooneye_m3_wx_4_change() {
    run_mooneye_test("testroms/m3_wx_4_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_wx_4_change_sprites() {
    run_mooneye_test("testroms/m3_wx_4_change_sprites.gb");
}

#[ignore]
#[test]
fn mooneye_m3_wx_5_change() {
    run_mooneye_test("testroms/m3_wx_5_change.gb");
}

#[ignore]
#[test]
fn mooneye_m3_wx_6_change() {
    run_mooneye_test("testroms/m3_wx_6_change.gb");
}

#[test]
fn mooneye_multicart_rom_8mb() {
    run_mooneye_test("testroms/multicart_rom_8Mb.gb");
}

#[test]
fn mooneye_oam_dma_restart() {
    run_mooneye_test("testroms/oam_dma_restart.gb");
}

#[test]
fn mooneye_oam_dma_start() {
    run_mooneye_test("testroms/oam_dma_start.gb");
}

#[test]
fn mooneye_oam_dma_timing() {
    run_mooneye_test("testroms/oam_dma_timing.gb");
}

#[test]
fn mooneye_pop_timing() {
    run_mooneye_test("testroms/pop_timing.gb");
}

#[test]
fn mooneye_push_timing() {
    run_mooneye_test("testroms/push_timing.gb");
}

#[test]
fn mooneye_ram_256kb() {
    run_mooneye_test("testroms/ram_256kb.gb");
}

#[test]
fn mooneye_ram_64kb() {
    run_mooneye_test("testroms/ram_64kb.gb");
}

#[test]
fn mooneye_rapid_di_ei() {
    run_mooneye_test("testroms/rapid_di_ei.gb");
}

#[test]
fn mooneye_reg_read() {
    run_mooneye_test("testroms/reg_read.gb");
}

#[test]
fn mooneye_ret_cc_timing() {
    run_mooneye_test("testroms/ret_cc_timing.gb");
}

#[test]
fn mooneye_ret_timing() {
    run_mooneye_test("testroms/ret_timing.gb");
}

#[test]
fn mooneye_reti_intr_timing() {
    run_mooneye_test("testroms/reti_intr_timing.gb");
}

#[test]
fn mooneye_reti_timing() {
    run_mooneye_test("testroms/reti_timing.gb");
}

#[test]
fn mooneye_rom_16mb() {
    run_mooneye_test("testroms/rom_16Mb.gb");
}

#[test]
fn mooneye_rom_1mb() {
    run_mooneye_test("testroms/rom_1Mb.gb");
}

#[test]
fn mooneye_rom_2mb() {
    run_mooneye_test("testroms/rom_2Mb.gb");
}

#[test]
fn mooneye_rom_4mb() {
    run_mooneye_test("testroms/rom_4Mb.gb");
}

#[test]
fn mooneye_rom_512kb() {
    run_mooneye_test("testroms/rom_512kb.gb");
}

#[test]
fn mooneye_rom_8mb() {
    run_mooneye_test("testroms/rom_8Mb.gb");
}

#[test]
fn mooneye_rst_timing() {
    run_mooneye_test("testroms/rst_timing.gb");
}

#[ignore]
#[test]
fn mooneye_sources_gs() {
    run_mooneye_test("testroms/sources-GS.gb");
}

// ══════════════════════════════════════════════════════════════════
// Blargg tests
// ══════════════════════════════════════════════════════════════════

#[test]
fn blargg_n01_registers() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/01-registers.gb");
}

#[test]
fn blargg_n02_len_ctr() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/02-len ctr.gb");
}

#[test]
fn blargg_n03_trigger() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/03-trigger.gb");
}

#[test]
fn blargg_n04_sweep() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/04-sweep.gb");
}

#[test]
fn blargg_n05_sweep_details() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/05-sweep details.gb");
}

#[test]
fn blargg_n06_overflow_on_trigger() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/06-overflow on trigger.gb");
}

#[test]
fn blargg_n07_len_sweep_period_sync() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/07-len sweep period sync.gb");
}

#[test]
#[ignore] // CGB-specific: length counter behavior differs from DMG
fn blargg_n08_len_ctr_during_power() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/08-len ctr during power.gb");
}

#[test]
#[ignore] // CGB-specific: wave read timing differs from DMG
fn blargg_n09_wave_read_while_on() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/09-wave read while on.gb");
}

#[test]
#[ignore] // CGB-specific: wave trigger behavior differs from DMG
fn blargg_n10_wave_trigger_while_on() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/10-wave trigger while on.gb");
}

#[test]
#[ignore] // CGB-specific: register clearing on power off differs from DMG
fn blargg_n11_regs_after_power() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/11-regs after power.gb");
}

#[test]
fn blargg_n12_wave() {
    run_blargg_test("testroms/artifacts/blargg/cgb_sound/rom_singles/12-wave.gb");
}

#[test]
fn blargg_cpu_instrs() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/cpu_instrs.gb");
}

#[test]
fn blargg_n01_special() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/01-special.gb");
}

#[test]
fn blargg_n02_interrupts() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/02-interrupts.gb");
}

#[test]
fn blargg_n03_op_sp_hl() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/03-op sp,hl.gb");
}

#[test]
fn blargg_n04_op_r_imm() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/04-op r,imm.gb");
}

#[test]
fn blargg_n05_op_rp() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/05-op rp.gb");
}

#[test]
fn blargg_n06_ld_r_r() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/06-ld r,r.gb");
}

#[test]
fn blargg_n07_jr_jp_call_ret_rst() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/07-jr,jp,call,ret,rst.gb");
}

#[test]
fn blargg_n08_misc_instrs() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/08-misc instrs.gb");
}

#[test]
fn blargg_n09_op_r_r() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/09-op r,r.gb");
}

#[test]
fn blargg_n10_bit_ops() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/10-bit ops.gb");
}

#[test]
fn blargg_n11_op_a_hl() {
    run_blargg_test("testroms/artifacts/blargg/cpu_instrs/individual/11-op a,(hl).gb");
}

#[test]
fn blargg_dmg_sound() {
    run_blargg_test("testroms/artifacts/blargg/dmg_sound/dmg_sound.gb");
}

#[test]
fn blargg_dmg_n09_wave_read_while_on() {
    run_blargg_test("testroms/artifacts/blargg/dmg_sound/rom_singles/09-wave read while on.gb");
}

#[test]
fn blargg_dmg_n10_wave_trigger_while_on() {
    run_blargg_test("testroms/artifacts/blargg/dmg_sound/rom_singles/10-wave trigger while on.gb");
}

#[test]
fn blargg_n12_wave_write_while_on() {
    run_blargg_test("testroms/artifacts/blargg/dmg_sound/rom_singles/12-wave write while on.gb");
}

#[test]
fn blargg_halt_bug() {
    run_blargg_test("testroms/artifacts/blargg/halt_bug.gb");
}

#[test]
fn blargg_instr_timing() {
    run_blargg_test("testroms/artifacts/blargg/instr_timing/instr_timing.gb");
}

#[test]
fn blargg_interrupt_time() {
    run_blargg_test("testroms/artifacts/blargg/interrupt_time/interrupt_time.gb");
}

#[test]
fn blargg_mem_timing() {
    run_blargg_test("testroms/artifacts/blargg/mem_timing-2/mem_timing.gb");
}

#[test]
fn blargg_n01_read_timing() {
    run_blargg_test("testroms/artifacts/blargg/mem_timing-2/rom_singles/01-read_timing.gb");
}

#[test]
fn blargg_n02_write_timing() {
    run_blargg_test("testroms/artifacts/blargg/mem_timing-2/rom_singles/02-write_timing.gb");
}

#[test]
fn blargg_n03_modify_timing() {
    run_blargg_test("testroms/artifacts/blargg/mem_timing-2/rom_singles/03-modify_timing.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_oam_bug() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/oam_bug.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_n1_lcd_sync() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/1-lcd_sync.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_n2_causes() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/2-causes.gb");
}

#[test]
fn blargg_n3_non_causes() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/3-non_causes.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_n4_scanline_timing() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/4-scanline_timing.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_n5_timing_bug() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/5-timing_bug.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_n6_timing_no_bug() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/6-timing_no_bug.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_n7_timing_effect() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/7-timing_effect.gb");
}

#[test]
#[ignore] // OAM corruption bug not implemented
fn blargg_n8_instr_effect() {
    run_blargg_test("testroms/artifacts/blargg/oam_bug/rom_singles/8-instr_effect.gb");
}

// ══════════════════════════════════════════════════════════════════
// GBMicrotest tests
// ══════════════════════════════════════════════════════════════════

#[test]
fn micro_n000_oam_lock() {
    run_micro_test("testroms/artifacts/gbmicrotest/000-oam_lock.gb");
}

#[test]
fn micro_n000_write_to_x8000() {
    run_micro_test("testroms/artifacts/gbmicrotest/000-write_to_x8000.gb");
}

#[test]
fn micro_n001_vram_unlocked() {
    run_micro_test("testroms/artifacts/gbmicrotest/001-vram_unlocked.gb");
}

#[test]
fn micro_n002_vram_locked() {
    run_micro_test("testroms/artifacts/gbmicrotest/002-vram_locked.gb");
}

#[test]
fn micro_n004_tima_boot_phase() {
    run_micro_test("testroms/artifacts/gbmicrotest/004-tima_boot_phase.gb");
}

#[test]
fn micro_n004_tima_cycle_timer() {
    run_micro_test("testroms/artifacts/gbmicrotest/004-tima_cycle_timer.gb");
}

#[test]
fn micro_n007_lcd_on_stat() {
    run_micro_test("testroms/artifacts/gbmicrotest/007-lcd_on_stat.gb");
}

#[test]
fn micro_n400_dma() {
    run_micro_test("testroms/artifacts/gbmicrotest/400-dma.gb");
}

#[test]
fn micro_n500_scx_timing() {
    run_micro_test("testroms/artifacts/gbmicrotest/500-scx-timing.gb");
}

#[test]
fn micro_n800_ppu_latch_scx() {
    run_micro_test("testroms/artifacts/gbmicrotest/800-ppu-latch-scx.gb");
}

#[test]
fn micro_n801_ppu_latch_scy() {
    run_micro_test("testroms/artifacts/gbmicrotest/801-ppu-latch-scy.gb");
}

#[test]
fn micro_n802_ppu_latch_tileselect() {
    run_micro_test("testroms/artifacts/gbmicrotest/802-ppu-latch-tileselect.gb");
}

#[test]
fn micro_n803_ppu_latch_bgdisplay() {
    run_micro_test("testroms/artifacts/gbmicrotest/803-ppu-latch-bgdisplay.gb");
}

#[test]
fn micro_audio_testbench() {
    run_micro_test("testroms/artifacts/gbmicrotest/audio_testbench.gb");
}

#[test]
fn micro_cpu_bus_1() {
    run_micro_test("testroms/artifacts/gbmicrotest/cpu_bus_1.gb");
}

#[test]
fn micro_div_inc_timing_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/div_inc_timing_a.gb");
}

#[test]
fn micro_div_inc_timing_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/div_inc_timing_b.gb");
}

#[test]
fn micro_dma_0x1000() {
    run_micro_test("testroms/artifacts/gbmicrotest/dma_0x1000.gb");
}

#[test]
fn micro_dma_0x9000() {
    run_micro_test("testroms/artifacts/gbmicrotest/dma_0x9000.gb");
}

#[test]
fn micro_dma_0xa000() {
    run_micro_test("testroms/artifacts/gbmicrotest/dma_0xA000.gb");
}

#[test]
fn micro_dma_0xc000() {
    run_micro_test("testroms/artifacts/gbmicrotest/dma_0xC000.gb");
}

#[test]
fn micro_dma_0xe000() {
    run_micro_test("testroms/artifacts/gbmicrotest/dma_0xE000.gb");
}

#[test]
fn micro_dma_basic() {
    run_micro_test("testroms/artifacts/gbmicrotest/dma_basic.gb");
}

#[test]
fn micro_dma_timing_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/dma_timing_a.gb");
}

#[test]
fn micro_flood_vram() {
    run_micro_test("testroms/artifacts/gbmicrotest/flood_vram.gb");
}

#[test]
fn micro_halt_bug() {
    run_micro_test("testroms/artifacts/gbmicrotest/halt_bug.gb");
}

#[test]
fn micro_halt_op_dupe() {
    run_micro_test("testroms/artifacts/gbmicrotest/halt_op_dupe.gb");
}

#[test]
fn micro_halt_op_dupe_delay() {
    run_micro_test("testroms/artifacts/gbmicrotest/halt_op_dupe_delay.gb");
}

#[test]
fn micro_hblank_int_di_timing_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_di_timing_a.gb");
}

#[test]
fn micro_hblank_int_di_timing_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_di_timing_b.gb");
}

#[test]
fn micro_hblank_int_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_if_a.gb");
}

#[test]
fn micro_hblank_int_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_if_b.gb");
}

#[test]
fn micro_hblank_int_l0() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_l0.gb");
}

#[test]
fn micro_hblank_int_l1() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_l1.gb");
}

#[test]
fn micro_hblank_int_l2() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_l2.gb");
}

#[test]
fn micro_hblank_int_scx0() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx0.gb");
}

#[test]
fn micro_hblank_int_scx0_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx0_if_a.gb");
}

#[test]
fn micro_hblank_int_scx0_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx0_if_b.gb");
}

#[test]
fn micro_hblank_int_scx0_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx0_if_c.gb");
}

#[test]
fn micro_hblank_int_scx0_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx0_if_d.gb");
}

#[test]
fn micro_hblank_int_scx1() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx1.gb");
}

#[test]
fn micro_hblank_int_scx1_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx1_if_a.gb");
}

#[test]
fn micro_hblank_int_scx1_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx1_if_b.gb");
}

#[test]
fn micro_hblank_int_scx1_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx1_if_c.gb");
}

#[test]
fn micro_hblank_int_scx1_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx1_if_d.gb");
}

#[test]
fn micro_hblank_int_scx1_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx1_nops_a.gb");
}

#[test]
fn micro_hblank_int_scx1_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx1_nops_b.gb");
}

#[test]
fn micro_hblank_int_scx2() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx2.gb");
}

#[test]
fn micro_hblank_int_scx2_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx2_if_a.gb");
}

#[test]
fn micro_hblank_int_scx2_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx2_if_b.gb");
}

#[test]
fn micro_hblank_int_scx2_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx2_if_c.gb");
}

#[test]
fn micro_hblank_int_scx2_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx2_if_d.gb");
}

#[test]
fn micro_hblank_int_scx2_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx2_nops_a.gb");
}

#[test]
fn micro_hblank_int_scx2_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx2_nops_b.gb");
}

#[test]
fn micro_hblank_int_scx3() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx3.gb");
}

#[test]
fn micro_hblank_int_scx3_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx3_if_a.gb");
}

#[test]
fn micro_hblank_int_scx3_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx3_if_b.gb");
}

#[test]
fn micro_hblank_int_scx3_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx3_if_c.gb");
}

#[test]
fn micro_hblank_int_scx3_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx3_if_d.gb");
}

#[test]
fn micro_hblank_int_scx3_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx3_nops_a.gb");
}

#[test]
fn micro_hblank_int_scx3_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx3_nops_b.gb");
}

#[test]
fn micro_hblank_int_scx4() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx4.gb");
}

#[test]
fn micro_hblank_int_scx4_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx4_if_a.gb");
}

#[test]
fn micro_hblank_int_scx4_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx4_if_b.gb");
}

#[test]
fn micro_hblank_int_scx4_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx4_if_c.gb");
}

#[test]
fn micro_hblank_int_scx4_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx4_if_d.gb");
}

#[test]
fn micro_hblank_int_scx4_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx4_nops_a.gb");
}

#[test]
fn micro_hblank_int_scx4_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx4_nops_b.gb");
}

#[test]
fn micro_hblank_int_scx5() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx5.gb");
}

#[test]
fn micro_hblank_int_scx5_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx5_if_a.gb");
}

#[test]
fn micro_hblank_int_scx5_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx5_if_b.gb");
}

#[test]
fn micro_hblank_int_scx5_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx5_if_c.gb");
}

#[test]
fn micro_hblank_int_scx5_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx5_if_d.gb");
}

#[test]
fn micro_hblank_int_scx5_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx5_nops_a.gb");
}

#[test]
fn micro_hblank_int_scx5_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx5_nops_b.gb");
}

#[test]
fn micro_hblank_int_scx6() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx6.gb");
}

#[test]
fn micro_hblank_int_scx6_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx6_if_a.gb");
}

#[test]
fn micro_hblank_int_scx6_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx6_if_b.gb");
}

#[test]
fn micro_hblank_int_scx6_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx6_if_c.gb");
}

#[test]
fn micro_hblank_int_scx6_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx6_if_d.gb");
}

#[test]
fn micro_hblank_int_scx6_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx6_nops_a.gb");
}

#[test]
fn micro_hblank_int_scx6_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx6_nops_b.gb");
}

#[test]
fn micro_hblank_int_scx7() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx7.gb");
}

#[test]
fn micro_hblank_int_scx7_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx7_if_a.gb");
}

#[test]
fn micro_hblank_int_scx7_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx7_if_b.gb");
}

#[test]
fn micro_hblank_int_scx7_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx7_if_c.gb");
}

#[test]
fn micro_hblank_int_scx7_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx7_if_d.gb");
}

#[test]
fn micro_hblank_int_scx7_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx7_nops_a.gb");
}

#[test]
fn micro_hblank_int_scx7_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_int_scx7_nops_b.gb");
}

#[test]
fn micro_hblank_scx2_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_scx2_if_a.gb");
}

#[test]
fn micro_hblank_scx3_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_scx3_if_a.gb");
}

#[test]
fn micro_hblank_scx3_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_scx3_if_b.gb");
}

#[test]
fn micro_hblank_scx3_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_scx3_if_c.gb");
}

#[test]
fn micro_hblank_scx3_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_scx3_if_d.gb");
}

#[test]
fn micro_hblank_scx3_int_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_scx3_int_a.gb");
}

#[test]
fn micro_hblank_scx3_int_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/hblank_scx3_int_b.gb");
}

#[test]
fn micro_int_hblank_halt_bug_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_bug_a.gb");
}

#[test]
fn micro_int_hblank_halt_bug_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_bug_b.gb");
}

#[test]
fn micro_int_hblank_halt_scx0() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx0.gb");
}

#[test]
fn micro_int_hblank_halt_scx1() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx1.gb");
}

#[test]
fn micro_int_hblank_halt_scx2() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx2.gb");
}

#[test]
fn micro_int_hblank_halt_scx3() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx3.gb");
}

#[test]
fn micro_int_hblank_halt_scx4() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx4.gb");
}

#[test]
fn micro_int_hblank_halt_scx5() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx5.gb");
}

#[test]
fn micro_int_hblank_halt_scx6() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx6.gb");
}

#[test]
fn micro_int_hblank_halt_scx7() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_halt_scx7.gb");
}

#[test]
fn micro_int_hblank_incs_scx0() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx0.gb");
}

#[test]
fn micro_int_hblank_incs_scx1() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx1.gb");
}

#[test]
fn micro_int_hblank_incs_scx2() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx2.gb");
}

#[test]
fn micro_int_hblank_incs_scx3() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx3.gb");
}

#[test]
fn micro_int_hblank_incs_scx4() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx4.gb");
}

#[test]
fn micro_int_hblank_incs_scx5() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx5.gb");
}

#[test]
fn micro_int_hblank_incs_scx6() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx6.gb");
}

#[test]
fn micro_int_hblank_incs_scx7() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_incs_scx7.gb");
}

#[test]
fn micro_int_hblank_nops_scx0() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx0.gb");
}

#[test]
fn micro_int_hblank_nops_scx1() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx1.gb");
}

#[test]
fn micro_int_hblank_nops_scx2() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx2.gb");
}

#[test]
fn micro_int_hblank_nops_scx3() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx3.gb");
}

#[test]
fn micro_int_hblank_nops_scx4() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx4.gb");
}

#[test]
fn micro_int_hblank_nops_scx5() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx5.gb");
}

#[test]
fn micro_int_hblank_nops_scx6() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx6.gb");
}

#[test]
fn micro_int_hblank_nops_scx7() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_hblank_nops_scx7.gb");
}

#[test]
fn micro_int_lyc_halt() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_lyc_halt.gb");
}

#[test]
fn micro_int_lyc_incs() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_lyc_incs.gb");
}

#[test]
fn micro_int_lyc_nops() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_lyc_nops.gb");
}

#[test]
fn micro_int_oam_halt() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_oam_halt.gb");
}

#[test]
fn micro_int_oam_incs() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_oam_incs.gb");
}

#[test]
fn micro_int_oam_nops() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_oam_nops.gb");
}

#[test]
fn micro_int_timer_halt() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_timer_halt.gb");
}

#[test]
fn micro_int_timer_halt_div_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_timer_halt_div_a.gb");
}

#[test]
fn micro_int_timer_halt_div_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_timer_halt_div_b.gb");
}

#[test]
fn micro_int_timer_incs() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_timer_incs.gb");
}

#[test]
fn micro_int_timer_nops() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_timer_nops.gb");
}

#[test]
fn micro_int_timer_nops_div_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_timer_nops_div_a.gb");
}

#[test]
fn micro_int_timer_nops_div_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_timer_nops_div_b.gb");
}

#[test]
fn micro_int_vblank1_halt() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_vblank1_halt.gb");
}

#[test]
fn micro_int_vblank1_incs() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_vblank1_incs.gb");
}

#[test]
fn micro_int_vblank1_nops() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_vblank1_nops.gb");
}

#[test]
fn micro_int_vblank2_halt() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_vblank2_halt.gb");
}

#[test]
fn micro_int_vblank2_incs() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_vblank2_incs.gb");
}

#[test]
fn micro_int_vblank2_nops() {
    run_micro_test("testroms/artifacts/gbmicrotest/int_vblank2_nops.gb");
}

#[test]
fn micro_is_if_set_during_ime0() {
    run_micro_test("testroms/artifacts/gbmicrotest/is_if_set_during_ime0.gb");
}

#[test]
fn micro_lcdon_halt_to_vblank_int_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_halt_to_vblank_int_a.gb");
}

#[test]
fn micro_lcdon_halt_to_vblank_int_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_halt_to_vblank_int_b.gb");
}

#[test]
fn micro_lcdon_nops_to_vblank_int_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_nops_to_vblank_int_a.gb");
}

#[test]
fn micro_lcdon_nops_to_vblank_int_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_nops_to_vblank_int_b.gb");
}

#[test]
fn micro_lcdon_to_if_oam_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_if_oam_a.gb");
}

#[test]
fn micro_lcdon_to_if_oam_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_if_oam_b.gb");
}

#[test]
fn micro_lcdon_to_ly1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_ly1_a.gb");
}

#[test]
fn micro_lcdon_to_ly1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_ly1_b.gb");
}

#[test]
fn micro_lcdon_to_ly2_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_ly2_a.gb");
}

#[test]
fn micro_lcdon_to_ly2_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_ly2_b.gb");
}

#[test]
fn micro_lcdon_to_ly3_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_ly3_a.gb");
}

#[test]
fn micro_lcdon_to_ly3_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_ly3_b.gb");
}

#[test]
fn micro_lcdon_to_lyc1_int() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_lyc1_int.gb");
}

#[test]
fn micro_lcdon_to_lyc2_int() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_lyc2_int.gb");
}

#[test]
fn micro_lcdon_to_lyc3_int() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_lyc3_int.gb");
}

#[test]
fn micro_lcdon_to_oam_int_l0() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_oam_int_l0.gb");
}

#[test]
fn micro_lcdon_to_oam_int_l1() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_oam_int_l1.gb");
}

#[test]
fn micro_lcdon_to_oam_int_l2() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_oam_int_l2.gb");
}

#[test]
fn micro_lcdon_to_oam_unlock_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_oam_unlock_a.gb");
}

#[test]
fn micro_lcdon_to_oam_unlock_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_oam_unlock_b.gb");
}

#[test]
fn micro_lcdon_to_oam_unlock_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_oam_unlock_c.gb");
}

#[test]
fn micro_lcdon_to_oam_unlock_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_oam_unlock_d.gb");
}

#[test]
fn micro_lcdon_to_stat0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat0_a.gb");
}

#[test]
fn micro_lcdon_to_stat0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat0_b.gb");
}

#[test]
fn micro_lcdon_to_stat0_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat0_c.gb");
}

#[test]
fn micro_lcdon_to_stat0_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat0_d.gb");
}

#[test]
fn micro_lcdon_to_stat1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat1_a.gb");
}

#[test]
fn micro_lcdon_to_stat1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat1_b.gb");
}

#[test]
fn micro_lcdon_to_stat1_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat1_c.gb");
}

#[test]
fn micro_lcdon_to_stat1_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat1_d.gb");
}

#[test]
fn micro_lcdon_to_stat1_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat1_e.gb");
}

#[test]
fn micro_lcdon_to_stat2_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat2_a.gb");
}

#[test]
fn micro_lcdon_to_stat2_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat2_b.gb");
}

#[test]
fn micro_lcdon_to_stat2_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat2_c.gb");
}

#[test]
fn micro_lcdon_to_stat2_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat2_d.gb");
}

#[test]
fn micro_lcdon_to_stat3_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat3_a.gb");
}

#[test]
fn micro_lcdon_to_stat3_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat3_b.gb");
}

#[test]
fn micro_lcdon_to_stat3_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat3_c.gb");
}

#[test]
fn micro_lcdon_to_stat3_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_to_stat3_d.gb");
}

#[test]
fn micro_lcdon_write_timing() {
    run_micro_test("testroms/artifacts/gbmicrotest/lcdon_write_timing.gb");
}

#[test]
fn micro_line_144_oam_int_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_144_oam_int_a.gb");
}

#[test]
fn micro_line_144_oam_int_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_144_oam_int_b.gb");
}

#[test]
fn micro_line_144_oam_int_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_144_oam_int_c.gb");
}

#[test]
fn micro_line_144_oam_int_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_144_oam_int_d.gb");
}

#[test]
fn micro_line_153_ly_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_ly_a.gb");
}

#[test]
fn micro_line_153_ly_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_ly_b.gb");
}

#[test]
fn micro_line_153_ly_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_ly_c.gb");
}

#[test]
fn micro_line_153_ly_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_ly_d.gb");
}

#[test]
fn micro_line_153_ly_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_ly_e.gb");
}

#[test]
fn micro_line_153_ly_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_ly_f.gb");
}

#[test]
fn micro_line_153_lyc0_int_inc_sled() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_int_inc_sled.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_a.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_b.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_c.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_d.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_e.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_f.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_g() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_g.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_h() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_h.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_i() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_i.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_j() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_j.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_k() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_k.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_l() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_l.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_m() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_m.gb");
}

#[test]
fn micro_line_153_lyc0_stat_timing_n() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc0_stat_timing_n.gb");
}

#[test]
fn micro_line_153_lyc153_stat_timing_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc153_stat_timing_a.gb");
}

#[test]
fn micro_line_153_lyc153_stat_timing_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc153_stat_timing_b.gb");
}

#[test]
fn micro_line_153_lyc153_stat_timing_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc153_stat_timing_c.gb");
}

#[test]
fn micro_line_153_lyc153_stat_timing_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc153_stat_timing_d.gb");
}

#[test]
fn micro_line_153_lyc153_stat_timing_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc153_stat_timing_e.gb");
}

#[test]
fn micro_line_153_lyc153_stat_timing_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc153_stat_timing_f.gb");
}

#[test]
fn micro_line_153_lyc_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc_a.gb");
}

#[test]
fn micro_line_153_lyc_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc_b.gb");
}

#[test]
fn micro_line_153_lyc_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc_c.gb");
}

#[test]
fn micro_line_153_lyc_int_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc_int_a.gb");
}

#[test]
fn micro_line_153_lyc_int_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_153_lyc_int_b.gb");
}

#[test]
fn micro_line_65_ly() {
    run_micro_test("testroms/artifacts/gbmicrotest/line_65_ly.gb");
}

#[test]
fn micro_ly_while_lcd_off() {
    run_micro_test("testroms/artifacts/gbmicrotest/ly_while_lcd_off.gb");
}

#[test]
fn micro_lyc1_int_halt_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_halt_a.gb");
}

#[test]
fn micro_lyc1_int_halt_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_halt_b.gb");
}

#[test]
fn micro_lyc1_int_if_edge_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_if_edge_a.gb");
}

#[test]
fn micro_lyc1_int_if_edge_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_if_edge_b.gb");
}

#[test]
fn micro_lyc1_int_if_edge_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_if_edge_c.gb");
}

#[test]
fn micro_lyc1_int_if_edge_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_if_edge_d.gb");
}

#[test]
fn micro_lyc1_int_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_nops_a.gb");
}

#[test]
fn micro_lyc1_int_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_int_nops_b.gb");
}

#[test]
fn micro_lyc1_write_timing_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_write_timing_a.gb");
}

#[test]
fn micro_lyc1_write_timing_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_write_timing_b.gb");
}

#[test]
fn micro_lyc1_write_timing_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_write_timing_c.gb");
}

#[test]
fn micro_lyc1_write_timing_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc1_write_timing_d.gb");
}

#[test]
fn micro_lyc2_int_halt_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc2_int_halt_a.gb");
}

#[test]
fn micro_lyc2_int_halt_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc2_int_halt_b.gb");
}

#[test]
fn micro_lyc_int_halt_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc_int_halt_a.gb");
}

#[test]
fn micro_lyc_int_halt_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/lyc_int_halt_b.gb");
}

#[test]
fn micro_mbc1_ram_banks() {
    run_micro_test("testroms/artifacts/gbmicrotest/mbc1_ram_banks.gb");
}

#[test]
fn micro_mbc1_rom_banks() {
    run_micro_test("testroms/artifacts/gbmicrotest/mbc1_rom_banks.gb");
}

#[test]
fn micro_minimal() {
    run_micro_test("testroms/artifacts/gbmicrotest/minimal.gb");
}

#[test]
fn micro_mode2_stat_int_to_oam_unlock() {
    run_micro_test("testroms/artifacts/gbmicrotest/mode2_stat_int_to_oam_unlock.gb");
}

#[test]
fn micro_oam_int_halt_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_halt_a.gb");
}

#[test]
fn micro_oam_int_halt_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_halt_b.gb");
}

#[test]
fn micro_oam_int_if_edge_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_if_edge_a.gb");
}

#[test]
fn micro_oam_int_if_edge_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_if_edge_b.gb");
}

#[test]
fn micro_oam_int_if_edge_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_if_edge_c.gb");
}

#[test]
fn micro_oam_int_if_edge_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_if_edge_d.gb");
}

#[test]
fn micro_oam_int_if_level_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_if_level_c.gb");
}

#[test]
fn micro_oam_int_if_level_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_if_level_d.gb");
}

#[test]
fn micro_oam_int_inc_sled() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_inc_sled.gb");
}

#[test]
fn micro_oam_int_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_nops_a.gb");
}

#[test]
fn micro_oam_int_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_int_nops_b.gb");
}

#[test]
fn micro_oam_read_l0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l0_a.gb");
}

#[test]
fn micro_oam_read_l0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l0_b.gb");
}

#[test]
fn micro_oam_read_l0_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l0_c.gb");
}

#[test]
fn micro_oam_read_l0_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l0_d.gb");
}

#[test]
fn micro_oam_read_l1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l1_a.gb");
}

#[test]
fn micro_oam_read_l1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l1_b.gb");
}

#[test]
fn micro_oam_read_l1_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l1_c.gb");
}

#[test]
fn micro_oam_read_l1_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l1_d.gb");
}

#[test]
fn micro_oam_read_l1_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l1_e.gb");
}

#[test]
fn micro_oam_read_l1_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_read_l1_f.gb");
}

#[test]
fn micro_oam_sprite_trashing() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_sprite_trashing.gb");
}

#[test]
fn micro_oam_write_l0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l0_a.gb");
}

#[test]
fn micro_oam_write_l0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l0_b.gb");
}

#[test]
fn micro_oam_write_l0_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l0_c.gb");
}

#[test]
fn micro_oam_write_l0_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l0_d.gb");
}

#[test]
fn micro_oam_write_l0_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l0_e.gb");
}

#[test]
fn micro_oam_write_l1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l1_a.gb");
}

#[test]
fn micro_oam_write_l1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l1_b.gb");
}

#[test]
fn micro_oam_write_l1_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l1_c.gb");
}

#[test]
fn micro_oam_write_l1_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l1_d.gb");
}

#[test]
fn micro_oam_write_l1_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l1_e.gb");
}

#[test]
fn micro_oam_write_l1_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/oam_write_l1_f.gb");
}

#[test]
fn micro_poweron() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron.gb");
}

#[test]
fn micro_poweron_bgp_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_bgp_000.gb");
}

#[test]
fn micro_poweron_div_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_div_000.gb");
}

#[test]
fn micro_poweron_div_004() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_div_004.gb");
}

#[test]
fn micro_poweron_div_005() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_div_005.gb");
}

#[test]
fn micro_poweron_dma_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_dma_000.gb");
}

#[test]
fn micro_poweron_if_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_if_000.gb");
}

#[test]
fn micro_poweron_joy_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_joy_000.gb");
}

#[test]
fn micro_poweron_lcdc_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_lcdc_000.gb");
}

#[test]
fn micro_poweron_ly_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_ly_000.gb");
}

#[test]
fn micro_poweron_ly_119() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_ly_119.gb");
}

#[test]
fn micro_poweron_ly_120() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_ly_120.gb");
}

#[test]
fn micro_poweron_ly_233() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_ly_233.gb");
}

#[test]
fn micro_poweron_ly_234() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_ly_234.gb");
}

#[test]
fn micro_poweron_lyc_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_lyc_000.gb");
}

#[test]
fn micro_poweron_oam_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_000.gb");
}

#[test]
fn micro_poweron_oam_005() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_005.gb");
}

#[test]
fn micro_poweron_oam_006() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_006.gb");
}

#[test]
fn micro_poweron_oam_069() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_069.gb");
}

#[test]
fn micro_poweron_oam_070() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_070.gb");
}

#[test]
fn micro_poweron_oam_119() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_119.gb");
}

#[test]
fn micro_poweron_oam_120() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_120.gb");
}

#[test]
fn micro_poweron_oam_121() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_121.gb");
}

#[test]
fn micro_poweron_oam_183() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_183.gb");
}

#[test]
fn micro_poweron_oam_184() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_184.gb");
}

#[test]
fn micro_poweron_oam_233() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_233.gb");
}

#[test]
fn micro_poweron_oam_234() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_234.gb");
}

#[test]
fn micro_poweron_oam_235() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_oam_235.gb");
}

#[test]
fn micro_poweron_obp0_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_obp0_000.gb");
}

#[test]
fn micro_poweron_obp1_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_obp1_000.gb");
}

#[test]
fn micro_poweron_sb_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_sb_000.gb");
}

#[test]
fn micro_poweron_sc_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_sc_000.gb");
}

#[test]
fn micro_poweron_scx_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_scx_000.gb");
}

#[test]
fn micro_poweron_scy_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_scy_000.gb");
}

#[test]
fn micro_poweron_stat_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_000.gb");
}

#[test]
fn micro_poweron_stat_005() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_005.gb");
}

#[test]
fn micro_poweron_stat_006() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_006.gb");
}

#[test]
fn micro_poweron_stat_007() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_007.gb");
}

#[test]
fn micro_poweron_stat_026() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_026.gb");
}

#[test]
fn micro_poweron_stat_027() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_027.gb");
}

#[test]
fn micro_poweron_stat_069() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_069.gb");
}

#[test]
fn micro_poweron_stat_070() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_070.gb");
}

#[test]
fn micro_poweron_stat_119() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_119.gb");
}

#[test]
fn micro_poweron_stat_120() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_120.gb");
}

#[test]
fn micro_poweron_stat_121() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_121.gb");
}

#[test]
fn micro_poweron_stat_140() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_140.gb");
}

#[test]
fn micro_poweron_stat_141() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_141.gb");
}

#[test]
fn micro_poweron_stat_183() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_183.gb");
}

#[test]
fn micro_poweron_stat_184() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_184.gb");
}

#[test]
fn micro_poweron_stat_234() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_234.gb");
}

#[test]
fn micro_poweron_stat_235() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_stat_235.gb");
}

#[test]
fn micro_poweron_tac_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_tac_000.gb");
}

#[test]
fn micro_poweron_tima_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_tima_000.gb");
}

#[test]
fn micro_poweron_tma_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_tma_000.gb");
}

#[test]
fn micro_poweron_vram_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_000.gb");
}

#[test]
fn micro_poweron_vram_025() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_025.gb");
}

#[test]
fn micro_poweron_vram_026() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_026.gb");
}

#[test]
fn micro_poweron_vram_069() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_069.gb");
}

#[test]
fn micro_poweron_vram_070() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_070.gb");
}

#[test]
fn micro_poweron_vram_139() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_139.gb");
}

#[test]
fn micro_poweron_vram_140() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_140.gb");
}

#[test]
fn micro_poweron_vram_183() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_183.gb");
}

#[test]
fn micro_poweron_vram_184() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_vram_184.gb");
}

#[test]
fn micro_poweron_wx_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_wx_000.gb");
}

#[test]
fn micro_poweron_wy_000() {
    run_micro_test("testroms/artifacts/gbmicrotest/poweron_wy_000.gb");
}

#[test]
fn micro_ppu_scx_vs_bgp() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_scx_vs_bgp.gb");
}

#[test]
fn micro_ppu_sprite0_scx0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx0_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx0_b.gb");
}

#[test]
fn micro_ppu_sprite0_scx1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx1_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx1_b.gb");
}

#[test]
fn micro_ppu_sprite0_scx2_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx2_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx2_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx2_b.gb");
}

#[test]
fn micro_ppu_sprite0_scx3_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx3_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx3_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx3_b.gb");
}

#[test]
fn micro_ppu_sprite0_scx4_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx4_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx4_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx4_b.gb");
}

#[test]
fn micro_ppu_sprite0_scx5_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx5_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx5_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx5_b.gb");
}

#[test]
fn micro_ppu_sprite0_scx6_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx6_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx6_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx6_b.gb");
}

#[test]
fn micro_ppu_sprite0_scx7_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx7_a.gb");
}

#[test]
fn micro_ppu_sprite0_scx7_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite0_scx7_b.gb");
}

#[test]
fn micro_ppu_sprite_testbench() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_sprite_testbench.gb");
}

#[test]
fn micro_ppu_spritex_vs_scx() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_spritex_vs_scx.gb");
}

#[test]
fn micro_ppu_win_vs_wx() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_win_vs_wx.gb");
}

#[test]
fn micro_ppu_wx_early() {
    run_micro_test("testroms/artifacts/gbmicrotest/ppu_wx_early.gb");
}

#[test]
fn micro_sprite4_0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_0_a.gb");
}

#[test]
fn micro_sprite4_0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_0_b.gb");
}

#[test]
fn micro_sprite4_1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_1_a.gb");
}

#[test]
fn micro_sprite4_1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_1_b.gb");
}

#[test]
fn micro_sprite4_2_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_2_a.gb");
}

#[test]
fn micro_sprite4_2_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_2_b.gb");
}

#[test]
fn micro_sprite4_3_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_3_a.gb");
}

#[test]
fn micro_sprite4_3_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_3_b.gb");
}

#[test]
fn micro_sprite4_4_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_4_a.gb");
}

#[test]
fn micro_sprite4_4_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_4_b.gb");
}

#[test]
fn micro_sprite4_5_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_5_a.gb");
}

#[test]
fn micro_sprite4_5_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_5_b.gb");
}

#[test]
fn micro_sprite4_6_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_6_a.gb");
}

#[test]
fn micro_sprite4_6_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_6_b.gb");
}

#[test]
fn micro_sprite4_7_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_7_a.gb");
}

#[test]
fn micro_sprite4_7_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite4_7_b.gb");
}

#[test]
fn micro_sprite_0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite_0_a.gb");
}

#[test]
fn micro_sprite_0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite_0_b.gb");
}

#[test]
fn micro_sprite_1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite_1_a.gb");
}

#[test]
fn micro_sprite_1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/sprite_1_b.gb");
}

#[test]
fn micro_stat_write_glitch_l0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l0_a.gb");
}

#[test]
fn micro_stat_write_glitch_l0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l0_b.gb");
}

#[test]
fn micro_stat_write_glitch_l0_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l0_c.gb");
}

#[test]
fn micro_stat_write_glitch_l143_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l143_a.gb");
}

#[test]
fn micro_stat_write_glitch_l143_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l143_b.gb");
}

#[test]
fn micro_stat_write_glitch_l143_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l143_c.gb");
}

#[test]
fn micro_stat_write_glitch_l143_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l143_d.gb");
}

#[test]
fn micro_stat_write_glitch_l154_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l154_a.gb");
}

#[test]
fn micro_stat_write_glitch_l154_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l154_b.gb");
}

#[test]
fn micro_stat_write_glitch_l154_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l154_c.gb");
}

#[test]
fn micro_stat_write_glitch_l154_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l154_d.gb");
}

#[test]
fn micro_stat_write_glitch_l1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l1_a.gb");
}

#[test]
fn micro_stat_write_glitch_l1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l1_b.gb");
}

#[test]
fn micro_stat_write_glitch_l1_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l1_c.gb");
}

#[test]
fn micro_stat_write_glitch_l1_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/stat_write_glitch_l1_d.gb");
}

#[test]
fn micro_temp() {
    run_micro_test("testroms/artifacts/gbmicrotest/temp.gb");
}

#[test]
fn micro_timer_div_phase_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_div_phase_c.gb");
}

#[test]
fn micro_timer_div_phase_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_div_phase_d.gb");
}

#[test]
fn micro_timer_tima_inc_256k_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_a.gb");
}

#[test]
fn micro_timer_tima_inc_256k_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_b.gb");
}

#[test]
fn micro_timer_tima_inc_256k_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_c.gb");
}

#[test]
fn micro_timer_tima_inc_256k_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_d.gb");
}

#[test]
fn micro_timer_tima_inc_256k_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_e.gb");
}

#[test]
fn micro_timer_tima_inc_256k_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_f.gb");
}

#[test]
fn micro_timer_tima_inc_256k_g() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_g.gb");
}

#[test]
fn micro_timer_tima_inc_256k_h() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_h.gb");
}

#[test]
fn micro_timer_tima_inc_256k_i() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_i.gb");
}

#[test]
fn micro_timer_tima_inc_256k_j() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_j.gb");
}

#[test]
fn micro_timer_tima_inc_256k_k() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_256k_k.gb");
}

#[test]
fn micro_timer_tima_inc_64k_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_64k_a.gb");
}

#[test]
fn micro_timer_tima_inc_64k_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_64k_b.gb");
}

#[test]
fn micro_timer_tima_inc_64k_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_64k_c.gb");
}

#[test]
fn micro_timer_tima_inc_64k_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_inc_64k_d.gb");
}

#[test]
fn micro_timer_tima_phase_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_a.gb");
}

#[test]
fn micro_timer_tima_phase_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_b.gb");
}

#[test]
fn micro_timer_tima_phase_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_c.gb");
}

#[test]
fn micro_timer_tima_phase_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_d.gb");
}

#[test]
fn micro_timer_tima_phase_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_e.gb");
}

#[test]
fn micro_timer_tima_phase_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_f.gb");
}

#[test]
fn micro_timer_tima_phase_g() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_g.gb");
}

#[test]
fn micro_timer_tima_phase_h() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_h.gb");
}

#[test]
fn micro_timer_tima_phase_i() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_i.gb");
}

#[test]
fn micro_timer_tima_phase_j() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_phase_j.gb");
}

#[test]
fn micro_timer_tima_reload_256k_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_a.gb");
}

#[test]
fn micro_timer_tima_reload_256k_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_b.gb");
}

#[test]
fn micro_timer_tima_reload_256k_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_c.gb");
}

#[test]
fn micro_timer_tima_reload_256k_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_d.gb");
}

#[test]
fn micro_timer_tima_reload_256k_e() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_e.gb");
}

#[test]
fn micro_timer_tima_reload_256k_f() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_f.gb");
}

#[test]
fn micro_timer_tima_reload_256k_g() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_g.gb");
}

#[test]
fn micro_timer_tima_reload_256k_h() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_h.gb");
}

#[test]
fn micro_timer_tima_reload_256k_i() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_i.gb");
}

#[test]
fn micro_timer_tima_reload_256k_j() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_j.gb");
}

#[test]
fn micro_timer_tima_reload_256k_k() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_reload_256k_k.gb");
}

#[test]
fn micro_timer_tima_write_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tima_write_a.gb");
}

#[test]
fn micro_timer_tima_write_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/timer_tma_write_b.gb");
}

#[test]
fn micro_toggle_lcdc() {
    run_micro_test("testroms/artifacts/gbmicrotest/toggle_lcdc.gb");
}

#[test]
fn micro_vblank2_int_halt_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_halt_a.gb");
}

#[test]
fn micro_vblank2_int_halt_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_halt_b.gb");
}

#[test]
fn micro_vblank2_int_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_if_a.gb");
}

#[test]
fn micro_vblank2_int_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_if_b.gb");
}

#[test]
fn micro_vblank2_int_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_if_c.gb");
}

#[test]
fn micro_vblank2_int_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_if_d.gb");
}

#[test]
fn micro_vblank2_int_inc_sled() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_inc_sled.gb");
}

#[test]
fn micro_vblank2_int_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_nops_a.gb");
}

#[test]
fn micro_vblank2_int_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank2_int_nops_b.gb");
}

#[test]
fn micro_vblank_int_halt_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_halt_a.gb");
}

#[test]
fn micro_vblank_int_halt_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_halt_b.gb");
}

#[test]
fn micro_vblank_int_if_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_if_a.gb");
}

#[test]
fn micro_vblank_int_if_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_if_b.gb");
}

#[test]
fn micro_vblank_int_if_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_if_c.gb");
}

#[test]
fn micro_vblank_int_if_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_if_d.gb");
}

#[test]
fn micro_vblank_int_inc_sled() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_inc_sled.gb");
}

#[test]
fn micro_vblank_int_nops_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_nops_a.gb");
}

#[test]
fn micro_vblank_int_nops_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vblank_int_nops_b.gb");
}

#[test]
fn micro_vram_read_l0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l0_a.gb");
}

#[test]
fn micro_vram_read_l0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l0_b.gb");
}

#[test]
fn micro_vram_read_l0_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l0_c.gb");
}

#[test]
fn micro_vram_read_l0_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l0_d.gb");
}

#[test]
fn micro_vram_read_l1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l1_a.gb");
}

#[test]
fn micro_vram_read_l1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l1_b.gb");
}

#[test]
fn micro_vram_read_l1_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l1_c.gb");
}

#[test]
fn micro_vram_read_l1_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_read_l1_d.gb");
}

#[test]
fn micro_vram_write_l0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l0_a.gb");
}

#[test]
fn micro_vram_write_l0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l0_b.gb");
}

#[test]
fn micro_vram_write_l0_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l0_c.gb");
}

#[test]
fn micro_vram_write_l0_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l0_d.gb");
}

#[test]
fn micro_vram_write_l1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l1_a.gb");
}

#[test]
fn micro_vram_write_l1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l1_b.gb");
}

#[test]
fn micro_vram_write_l1_c() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l1_c.gb");
}

#[test]
fn micro_vram_write_l1_d() {
    run_micro_test("testroms/artifacts/gbmicrotest/vram_write_l1_d.gb");
}

#[test]
fn micro_wave_write_to_0xc003() {
    run_micro_test("testroms/artifacts/gbmicrotest/wave_write_to_0xC003.gb");
}

#[test]
fn micro_win0_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win0_a.gb");
}

#[test]
fn micro_win0_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win0_b.gb");
}

#[test]
fn micro_win0_scx3_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win0_scx3_a.gb");
}

#[test]
fn micro_win0_scx3_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win0_scx3_b.gb");
}

#[test]
fn micro_win10_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win10_a.gb");
}

#[test]
fn micro_win10_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win10_b.gb");
}

#[test]
fn micro_win10_scx3_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win10_scx3_a.gb");
}

#[test]
fn micro_win10_scx3_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win10_scx3_b.gb");
}

#[test]
fn micro_win11_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win11_a.gb");
}

#[test]
fn micro_win11_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win11_b.gb");
}

#[test]
fn micro_win12_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win12_a.gb");
}

#[test]
fn micro_win12_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win12_b.gb");
}

#[test]
fn micro_win13_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win13_a.gb");
}

#[test]
fn micro_win13_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win13_b.gb");
}

#[test]
fn micro_win14_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win14_a.gb");
}

#[test]
fn micro_win14_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win14_b.gb");
}

#[test]
fn micro_win15_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win15_a.gb");
}

#[test]
fn micro_win15_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win15_b.gb");
}

#[test]
fn micro_win1_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win1_a.gb");
}

#[test]
fn micro_win1_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win1_b.gb");
}

#[test]
fn micro_win2_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win2_a.gb");
}

#[test]
fn micro_win2_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win2_b.gb");
}

#[test]
fn micro_win3_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win3_a.gb");
}

#[test]
fn micro_win3_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win3_b.gb");
}

#[test]
fn micro_win4_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win4_a.gb");
}

#[test]
fn micro_win4_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win4_b.gb");
}

#[test]
fn micro_win5_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win5_a.gb");
}

#[test]
fn micro_win5_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win5_b.gb");
}

#[test]
fn micro_win6_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win6_a.gb");
}

#[test]
fn micro_win6_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win6_b.gb");
}

#[test]
fn micro_win7_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win7_a.gb");
}

#[test]
fn micro_win7_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win7_b.gb");
}

#[test]
fn micro_win8_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win8_a.gb");
}

#[test]
fn micro_win8_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win8_b.gb");
}

#[test]
fn micro_win9_a() {
    run_micro_test("testroms/artifacts/gbmicrotest/win9_a.gb");
}

#[test]
fn micro_win9_b() {
    run_micro_test("testroms/artifacts/gbmicrotest/win9_b.gb");
}

// ══════════════════════════════════════════════════════════════════
// Unit tests for timer mechanics
// ══════════════════════════════════════════════════════════════════


#[test]
fn timer_falling_edge_basic() {
    let mut cpu = CPU::new();
    cpu.program_counter = 0x100;
    cpu.booting = false;
    cpu.memory[0xFF05] = 0x00;
    cpu.memory[0xFF06] = 0x00;
    cpu.memory[0xFF07] = 0x00;
    cpu.write_byte(0xFF07, 0x05); // 262144 Hz
    for _ in 0..4 { cpu.tick_timer_4t(); }
    assert_eq!(cpu.memory[0xFF05], 1, "TIMA should be 1 after 4 M-cycles at 262144 Hz");
}

#[test]
fn timer_div_reset_causes_tick() {
    let mut cpu = CPU::new();
    cpu.program_counter = 0x100;
    cpu.booting = false;
    cpu.memory[0xFF05] = 0x00;
    cpu.memory[0xFF06] = 0x00;
    cpu.write_byte(0xFF07, 0x04); // 4096 Hz, monitors bit 9
    for _ in 0..128 { cpu.tick_timer_4t(); } // bit 9 is now 1
    let tima_before = cpu.memory[0xFF05];
    cpu.write_byte(0xFF04, 0x00); // DIV reset → falling edge
    assert_eq!(cpu.memory[0xFF05], tima_before + 1, "DIV reset should cause TIMA tick");
}
